### ISSUE TITLE
BGS Identified Bugs - DataTypes - dates & strings

### ISSUE THREAD

**Issue by KoalaGeo** [BritishGeologicalSurvey/pyagsapi#55]
Bugs ID: 

- [ ] Using the excel to ags converter I cant get it to handle dates – whatever format I type the date in on an excel file it doesn’t appear in the ags file
- [ ] SAMP_REF is datatype X (text) but it won’t recognise numbers (I thought anything in a text field could be read as text)

**Comment by asitha-sena** [comment]
@KoalaGeo I manage to recreate the first two issues using v0.3.6 of the python_ags4 library. The good news is that both issues seem to have been fixed in v0.3.7 ([see changelog](https://gitlab.com/ags-data-format-wg/ags-python-library/-/blob/main/changelog.txt)). I did a quick check with the current version (0.4.1) and things seem to work just fine.

**Comment by KoalaGeo** [comment]
Updating to [v0.4.1](https://gitlab.com/ags-data-format-wg/ags-python-library/-/tags/0.4.1) will fix this issue
